### ISSUE TITLE
ArcHud3-Classic Taints TargetOfTarget frame

### ISSUE THREAD

**Issue by DDCorkum** [nyyr/ArcHUD3#44] opened 2019-09-22 15:02 UTC
**Issue:**  ArcHud3 applies taint to the TargetOfTarget unit frame, preventing it from appearing during combat.

**Background:**  The ToT frame appears in the bottom-right corner of the target unit frame, and on Classic it automatically appears when you are fighting an enemy who is targeting someone (such as yourself),

**Steps to Reproduce:**  Enter combat.  There will be numerous instances of this error per second while combat continues, as measured by bug catching addons.

**Workaround:**  None that I can find.  The frame is "secure" and will refuse to perform its function in combat if it senses taint, to prevent cheating.

**Taint Log Info:** 
9/22 09:00:21.771  Interface\FrameXML\TargetFrame.lua:908 TargetofTarget_Update()
9/22 09:00:21.771  **An action was blocked in combat because of taint from ArcHUD3-classic - TargetFrameToT:Show()**
9/22 09:00:21.771      Interface\FrameXML\TargetFrame.lua:910 TargetofTarget_Update()
9/22 09:00:21.771      Interface\FrameXML\TargetFrame.lua:420 TargetFrame_OnUpdate()
9/22 09:00:21.771      TargetFrame:OnUpdate()

**Comment by DDCorkum** [comment] 2019-09-22 15:25
Upon further investigation, this is caused by the global taint of UnitAura() that has far-reaching impacts.  Applying a single line-of-code fix suggested in issue #45 will eliminate this issue.

https://github.com/nyyr/ArcHUD3/issues/45

**Comment by nyyr** [comment] 2019-09-22 16:00
Duplicate of #45

**Closed by nyyr** 2019-09-22 16:00 UTC
